# For more information see:
# - https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
# - https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputsoutput_id

# The action can be referenced in workflows like:
# - ngxs/store/.github/actions/setup@master
# - ./.github/actions/setup

name: setup
description: Set up environment
inputs:
  NODE_VERSION:
    description: Node version
    required: true
    default: 16.x
  GITHUB_REF_NAME:
    description: Branch name
    required: true
    default: ${{ github.ref_name }}
  GITHUB_SHA:
    description: Commit hash
    required: true
    default: ${{ github.sha }}

runs:
  using: 'composite'
  steps:
    # This action should be called in the parent workflow before this composite action.
    # Composite action, as well as any other files, can not be referenced by a relative path before the sources are checked out.
    # - name: Checkout sources
    #   uses: actions/checkout@v3
    #   with:
    #     fetch-depth: 0
    #     ref: ${{ inputs.GITHUB_SHA }}

    - name: Don't save Bash session history
      shell: bash
      run: unset HISTFILE

    - name: Use Node.js ${{ inputs.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.NODE_VERSION }}
        check-latest: true

    - name: Configure kernel (increase watchers)
      shell: bash
      run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

    - name: Get variables (branch name, commit hash)
      shell: bash
      id: get-variables
      run: |
        echo "::set-output name=shortref::$(echo ${inputs.GITHUB_REF_NAME})";
        echo "::set-output name=commitsha::$(echo ${inputs.GITHUB_SHA})";

    - name: Workspace cache
      uses: actions/cache@v3
      id: workspace-cache
      env:
        cache-name: workspace-cache
      with:
        path: |
          ~/.cache
          ./node_modules
          ./@ngxs
          ./integrations/hello-world-ng11-ivy/dist-integration
          ./integrations/hello-world-ng12-ivy/dist-integration
          ./integrations/hello-world-ng13-ivy/dist-integration
          ./integrations/hello-world-ng14-ivy/dist-integration
        key: ${{ runner.os }}-node-${{ inputs.NODE_VERSION }}-yarn-${{ hashFiles('**/yarn.lock') }}-branch-${{ steps.get-variables.outputs.shortref }}-workspace-${{ steps.get-variables.outputs.commitsha }}
        restore-keys: |
          ${{ runner.os }}-node-${{ inputs.NODE_VERSION }}-yarn-${{ hashFiles('**/yarn.lock') }}-branch-${{ steps.get-variables.outputs.shortref }}-workspace-
          ${{ runner.os }}-node-${{ inputs.NODE_VERSION }}-yarn-${{ hashFiles('**/yarn.lock') }}-branch-
          ${{ runner.os }}-node-${{ inputs.NODE_VERSION }}-yarn-
          ${{ runner.os }}-

    - name: Install project dependencies
      shell: bash
      run: yarn install --frozen-lockfile --non-interactive
