# For more information see:
# - https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
# - https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputsoutput_id

# The action can be referenced in workflows like:
# - ngxs/store/.github/actions/setup@master
# - ./.github/actions/setup

name: setup
description: Set up environment

inputs:
  node-version:
    description: Node version
    required: true
    default: 22.x
  github-ref-name:
    description: Branch name
    required: true
    default: ${{ github.ref_name }}
  github-sha:
    description: Commit hash
    required: true
    default: ${{ github.sha }}

runs:
  using: 'composite'
  steps:
    - name: Don't save Bash session history
      shell: bash
      run: unset HISTFILE

    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: https://registry.npmjs.org
        check-latest: true
        cache: 'yarn'

    - name: Configure kernel (increase watchers)
      shell: bash
      run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

    - name: Workspace cache
      # Skip the workspace cache, because it might be slowing things down. Using setup-node action above instead
      if: false
      uses: actions/cache@v4
      id: workspace-cache
      env:
        cache-name: workspace-cache
      with:
        path: |
          ~/.cache
          ./node_modules
          ./@ngxs
          ./integrations/hello-world-ng21/dist-integration
        key: ${{ runner.os }}-node-${{ inputs.node-version }}-yarn-${{ hashFiles('**/yarn.lock') }}-branch-${{ inputs.github-ref-name }}-sha-${{ inputs.github-sha }}
        restore-keys: |
          ${{ runner.os }}-node-${{ inputs.node-version }}-yarn-${{ hashFiles('**/yarn.lock') }}-branch-${{ inputs.github-ref-name }}-sha-
          ${{ runner.os }}-node-${{ inputs.node-version }}-yarn-${{ hashFiles('**/yarn.lock') }}-branch-
          ${{ runner.os }}-node-${{ inputs.node-version }}-yarn-
          ${{ runner.os }}-

    - name: Download ngxs build artifacts
      uses: actions/download-artifact@v4
      with:
        name: ngxs-build
        path: ./@ngxs
      continue-on-error: true

    - name: Install project dependencies
      shell: bash
      run: yarn install --frozen-lockfile --non-interactive

    - name: Install tutorials dependencies
      shell: bash
      run: yarn tutorials:install
