version: "2"
plugins:
  tslint:
    enabled: true
    config: tslint.json
  nodesecurity:
    enabled: true
checks:
  method-complexity:
    config:
      threshold: 20
exclude_paths:
  - ".github/"
  - "assets/"
  - "docs/"
  - "packages/**/tests/"
  - "integration/"
  - "tools/"
ratings:
   paths:
   - "packages/**/**.ts"
