version: '2'
plugins:
  nodesecurity:
    enabled: true
checks:
  method-complexity:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 50
exclude_patterns:
  - '.github/'
  - 'assets/'
  - 'docs/'
  - 'packages/**/tests/'
  - 'packages/store/schematics/src/utils/ng-utils/'
  - 'integrations/'
  - 'integration/'
  - 'tools/'
ratings:
  paths:
    - 'packages/**/**.ts'
