# For more information see:
# - https://docs.github.com/en/actions/using-workflows/reusing-workflows
# - https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations

# Note:
# The workflow can be referenced in other workflows like:
# - ngxs/store/.github/actions/check-build-artifacts.yml@master
# - ./.github/actions/check-build-artifacts.yml

name: check-build-artifacts

runs:
  using: 'composite'
  steps:
    - name: Check @ngxs build artifacts
      run: |
        echo "Making sure the build artifact directories exist."
        [[ -d $DEVTOOLS_PLUG_ART ]] && echo "$DEVTOOLS_PLUG_ART $OK" || echo "$DEVTOOLS_PLUG_ART $FAILURE" exit 1
        [[ -d $FORM_PLUG_ART ]] && echo "$FORM_PLUG_ART $OK" || echo "$DEVTOOLS_PLUG_ART $FAILURE" exit 1
        [[ -d $HMR_PLUG_ART ]] && echo "$HMR_PLUG_ART $OK" || echo "$HMR_PLUG_ART $FAILURE" exit 1
        [[ -d $LOGGER_PLUG_ART ]] && echo "$LOGGER_PLUG_ART $OK" || echo "$LOGGER_PLUG_ART $FAILURE" exit 1
        [[ -d $ROUTER_PLUG_ART ]] && echo "$ROUTER_PLUG_ART $OK" || echo "$ROUTER_PLUG_ART $FAILURE" exit 1
        [[ -d $STORAGE_PLUG_ART ]] && echo "$STORAGE_PLUG_ART $OK" || echo "$STORAGE_PLUG_ART $FAILURE" exit 1
        [[ -d $STORE_ART ]] && echo "$STORE_ART $OK" || echo "$STORE_ART $FAILURE" exit 1
        [[ -d $WEBSOCKET_PLUG_ART ]] && echo "$WEBSOCKET_PLUG_ART $OK" || echo "$WEBSOCKET_PLUG_ART $FAILURE" exit 1
      env:
        OK: 'exists'
        FAILURE: 'does not exist'
        DEVTOOLS_PLUG_ART: './@ngxs/devtools-plugin'
        FORM_PLUG_ART: './@ngxs/form-plugin'
        HMR_PLUG_ART: './@ngxs/hmr-plugin'
        LOGGER_PLUG_ART: './@ngxs/logger-plugin'
        ROUTER_PLUG_ART: './@ngxs/router-plugin'
        STORAGE_PLUG_ART: './@ngxs/storage-plugin'
        STORE_ART: './@ngxs/store'
        WEBSOCKET_PLUG_ART: './@ngxs/websocket-plugin'
