# For more information see:
# - https://docs.github.com/en/actions/using-workflows/reusing-workflows
# - https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations

# Note:
# This workflow might be used after code is merged into the master branch.
# The workflow is references in other workflows like: ngxs/store/.github/workflows/get-variables.yml@master

name: get-variables

on:
  workflow_call:
    outputs:
      shortref:
        description: "Branch name"
        value: ${{ jobs.get-variables.outputs.shortref }}
      commitsha:
        description: "GitHub commit SHA"
        value: ${{ jobs.get-variables.outputs.commitsha }}
      yarncachedir:
        description: "Yarn cache directory"
        value: ${{ jobs.get-variables.outputs.yarncachedir }}

jobs:
  get-variables:
    name: Get variables (branch name, commit hash, yarn cache directory)
    runs-on: ubuntu-latest
    outputs:
      shortref: ${{ steps.get-variables.outputs.shortref }}
      commitsha: ${{ steps.get-variables.outputs.commitsha }}
      yarncachedir: ${{ steps.get-variables.outputs.yarncachedir }}
    steps:
      - id: get-variables
        run: |
          echo "::set-output name=shortref::${GITHUB_REF#refs/*/}";
          echo "::set-output name=commitsha::$(echo ${GITHUB_SHA})";
          echo "::set-output name=yarncachedir::$(yarn cache dir)";
