# For more information see:
# - https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# - https://docs.github.com/en/actions/learn-github-actions/contexts#github-context

name: release

on:
  release:
    types:
      - created

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref_name }}.${{ github.sha }}.release
  cancel-in-progress: true

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node-version: 16.x
          github-ref-name: ${{ github.ref_name }}
          github-sha: ${{ github.sha }}

      - name: Build NGXS
        run: yarn build

  release-test:
    runs-on: ubuntu-latest
    needs: release-build

    strategy:
      matrix:
        node-version: [16.x]
        script: [lint, eslint, 'test:ci']

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}
          github-ref-name: ${{ github.ref_name }}
          github-sha: ${{ github.sha }}

      - name: Run ${{ matrix.script }}
        run: yarn ${{ matrix.script }}

      - name: Upload coverage results to Code Climate
        if: ${{ matrix.script == 'test:ci' }}
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > /tmp/cc-test-reporter
          chmod +x /tmp/cc-test-reporter
          /tmp/cc-test-reporter after-build --coverage-input-type lcov --exit-code 0
        env:
          CC_TEST_REPORTER_ID: 3f4c9a9d57ded045e0f9ab5d23e5bbcbf709bb85637bea555f1233e72134b818 # TODO: better store it in the repository secrets. Name the variable: CC_TEST_REPORTER_ID. Then delete this line and uncomment the next one
          # CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

  release-integration-test:
    runs-on: ubuntu-latest
    needs: release-build

    strategy:
      matrix:
        node-version: [16.x]
        script:
          - 'integration:ng7'
          - 'integration:ng8'
          - 'integration:ng9:ivy:off'
          - 'integration:ng9:ivy'
          - 'integration:ng10:ivy:off'
          - 'integration:ng10:ivy'
          - 'integration:ng11:ivy:off'
          - 'integration:ng11:ivy'
          - 'integration:ng12:ivy'
          - 'integration:ng13:ivy'
          - 'integration:ng14:ivy'
          - 'test:types'

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}
          github-ref-name: ${{ github.ref_name }}
          github-sha: ${{ github.sha }}

      - name: Run ${{ matrix.script }}
        run: yarn ${{ matrix.script }}

      - name: Upload an integration test artifact
        if: ${{ matrix.script == 'integration:ng11:ivy' || matrix.script == 'integration:ng12:ivy' || matrix.script == 'integration:ng13:ivy' || matrix.script == 'integration:ng14:ivy' }}
        uses: ./.github/actions/upload-integration-test-artifact
        with:
          script: ${{ matrix.script }}

  release-bundlesize:
    runs-on: ubuntu-latest
    needs: release-integration-test

    strategy:
      matrix:
        node-version: [16.x]
        script: [bundlesize]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}
          github-ref-name: ${{ github.ref_name }}
          github-sha: ${{ github.sha }}

      - name: Download integration test artifacts
        uses: ./.github/actions/download-integration-test-artifacts

      - name: Run ${{ matrix.script }}
        run: yarn ${{ matrix.script }}

  release-publish:
    runs-on: ubuntu-latest
    environment: npm-publish
    needs: [release-build, release-test, release-integration-test, release-bundlesize]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
        with:
          node-version: 16.x
          github-ref-name: ${{ github.ref_name }}
          github-sha: ${{ github.sha }}

      - name: Check @ngxs build artifacts
        uses: ./.github/actions/check-build-artifacts

      - name: Production release - publish tagged builds to all @ngxs packages
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          yarn publish:tagged
          echo "Security: remove ~/.npmrc from the runner overwriting it with zeros several times."
          find ~/.npmrc -exec shred -fuz {} +
