# For more information see:
# - https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# - https://docs.github.com/en/actions/learn-github-actions/contexts#github-context

name: release

# on:
#   push:
#     branches: [master]
#     tags: ['v.*']
## Instead of the above, it is better to trigger the workflow when a release is manually created on GutHub via the releases page.
## The above was replicated based on the CircleCI workflows file which does not use the best practices when using GutHub with GitHub Actions CI.
on:
  release:
    types:
      - created

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref_name }}.${{ github.sha }}.release
  cancel-in-progress: true

jobs:
  ## the reusable job will work after the PR is merged and files are committed to the master branch
  # get-variables:
  #   uses: ngxs/store/.github/workflows/get-variables.yml@master # <- references a reusable workflow file and a branch

  build-release_prod:
    runs-on: ubuntu-latest
    # needs: get-variables # this can be uncommented after the reusable job works (see above)

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Don't save Bash session history
        run: unset HISTFILE

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true

      - name: Configure kernel (increase watchers)
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

      # this step might be replaced with a reusable workflow get-variables.yml (see above)
      - name: Get variables (branch name, commit hash, yarn cache directory)
        id: get-variables
        run: |
          echo "::set-output name=shortref::${GITHUB_REF#refs/*/}";
          echo "::set-output name=commitsha::$(echo ${GITHUB_SHA})";
          echo "::set-output name=yarncachedir::$(yarn cache dir)";

      - name: Workspace cache
        uses: actions/cache@v3
        id: workspace-cache
        env:
          cache-name: workspace-cache
        with:
          path: |
            ~/.cache
            ./node_modules
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-yarn-${{ hashFiles('**/yarn.lock') }}-branch-${{ steps.get-variables.outputs.shortref }}-workspace-${{ steps.get-variables.outputs.commitsha }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-yarn-${{ hashFiles('**/yarn.lock') }}-branch-${{ steps.get-variables.outputs.shortref }}-workspace-
            ${{ runner.os }}-node-${{ matrix.node-version }}-yarn-${{ hashFiles('**/yarn.lock') }}-branch-
            ${{ runner.os }}-node-${{ matrix.node-version }}-yarn-
            ${{ runner.os }}-
          ## the above might be replaced with the commented code beneath if a reusable workflow get-variables.yml is used (see above)
          # key: ${{ runner.os }}-node-${{ matrix.node-version }}-yarn-${{ hashFiles('**/yarn.lock') }}-branch-${{ needs.get-variables.outputs.shortref }}-workspace-${{ needs.get-variables.outputs.commitsha }}
          # restore-keys: |
          #   ${{ runner.os }}-node-${{ matrix.node-version }}-yarn-${{ hashFiles('**/yarn.lock') }}-branch-${{ needs.get-variables.outputs.shortref }}-workspace-
          #   ${{ runner.os }}-node-${{ matrix.node-version }}-yarn-${{ hashFiles('**/yarn.lock') }}-branch-
          #   ${{ runner.os }}-node-${{ matrix.node-version }}-yarn-
          #   ${{ runner.os }}-

      # TODO: verify if this is needed at all
      # - name: Set NPM global path
      #   run: echo 'prefix = ~/.npm' > ~/.npmrc

      - name: Install project dependencies
        run: yarn install --frozen-lockfile --non-interactive

      - name: Compile NGXS and create a pack
        run: |
          yarn build
          yarn pack --filename ./dist/ngxs-core.tgz

      ## All steps marked with this comment don't seem to be needed for tagged builds (aka releases), because each tagged build will happen only after a respective dev build,
      ## if releases are built off the trunk after dev builds.
      ## Dev builds happen automatically when something is merged into the trunk (it should not be possible to push into the trunk directly) and there is no tag.
      # - name: Lint - TSLint
      #   run: yarn lint

      ## All steps marked with this comment don't seem to be needed for tagged builds (aka releases), because each tagged build will happen only after a respective dev build,
      ## if releases are built off the trunk after dev builds.
      ## Dev builds happen automatically when something is merged into the trunk (it should not be possible to push into the trunk directly) and there is no tag.
      # - name: Lint - ESLint
      #   run: yarn eslint

      ## All steps marked with this comment don't seem to be needed for tagged builds (aka releases), because each tagged build will happen only after a respective dev build,
      ## if releases are built off the trunk after dev builds.
      ## Dev builds happen automatically when something is merged into the trunk (it should not be possible to push into the trunk directly) and there is no tag.
      # - name: Unit Tests
      #   run: yarn test:ci

      ## All steps marked with this comment don't seem to be needed for tagged builds (aka releases), because each tagged build will happen only after a respective dev build,
      ## if releases are built off the trunk after dev builds.
      ## Dev builds happen automatically when something is merged into the trunk (it should not be possible to push into the trunk directly) and there is no tag.
      ## This step was commented in the CircleCI workflows config.
      ## - name: Integration Tests
      ##   run: yarn test:ci:integration

      ## All steps marked with this comment don't seem to be needed for tagged builds (aka releases), because each tagged build will happen only after a respective dev build,
      ## if releases are built off the trunk after dev builds.
      ## Dev builds happen automatically when something is merged into the trunk (it should not be possible to push into the trunk directly) and there is no tag.
      ## This step was commented in the CircleCI workflows config.
      ## - name: E2E Tests
      ##   run: yarn test:ci:e2e

      ## All steps marked with this comment don't seem to be needed for tagged builds (aka releases), because each tagged build will happen only after a respective dev build,
      ## if releases are built off the trunk after dev builds.
      ## Dev builds happen automatically when something is merged into the trunk (it should not be possible to push into the trunk directly) and there is no tag.
      ## This step was commented in the CircleCI workflows config.
      ## - name: Integration Tests - SSR
      ##   run: yarn test:ci:integration:ssr

      ## All steps marked with this comment don't seem to be needed for tagged builds (aka releases), because each tagged build will happen only after a respective dev build,
      ## if releases are built off the trunk after dev builds.
      ## Dev builds happen automatically when something is merged into the trunk (it should not be possible to push into the trunk directly) and there is no tag.
      # - name: Integration Tests - ng7
      #   run: yarn integration:ng7

      ## All steps marked with this comment don't seem to be needed for tagged builds (aka releases), because each tagged build will happen only after a respective dev build,
      ## if releases are built off the trunk after dev builds.
      ## Dev builds happen automatically when something is merged into the trunk (it should not be possible to push into the trunk directly) and there is no tag.
      # - name: Integration Tests - ng8
      #   run: yarn integration:ng8

      ## All steps marked with this comment don't seem to be needed for tagged builds (aka releases), because each tagged build will happen only after a respective dev build,
      ## if releases are built off the trunk after dev builds.
      ## Dev builds happen automatically when something is merged into the trunk (it should not be possible to push into the trunk directly) and there is no tag.
      # - name: Integration Tests - ng9, Ivy off
      #   run: yarn integration:ng9:ivy:off

      ## All steps marked with this comment don't seem to be needed for tagged builds (aka releases), because each tagged build will happen only after a respective dev build,
      ## if releases are built off the trunk after dev builds.
      ## Dev builds happen automatically when something is merged into the trunk (it should not be possible to push into the trunk directly) and there is no tag.
      # - name: Integration Tests - ng9, Ivy
      #   run: yarn integration:ng9:ivy

      ## All steps marked with this comment don't seem to be needed for tagged builds (aka releases), because each tagged build will happen only after a respective dev build,
      ## if releases are built off the trunk after dev builds.
      ## Dev builds happen automatically when something is merged into the trunk (it should not be possible to push into the trunk directly) and there is no tag.
      # - name: Integration Tests - ng10, Ivy off
      #   run: yarn integration:ng10:ivy:off

      ## All steps marked with this comment don't seem to be needed for tagged builds (aka releases), because each tagged build will happen only after a respective dev build,
      ## if releases are built off the trunk after dev builds.
      ## Dev builds happen automatically when something is merged into the trunk (it should not be possible to push into the trunk directly) and there is no tag.
      # - name: Integration Tests - ng10, Ivy
      #   run: yarn integration:ng10:ivy

      ## All steps marked with this comment don't seem to be needed for tagged builds (aka releases), because each tagged build will happen only after a respective dev build,
      ## if releases are built off the trunk after dev builds.
      ## Dev builds happen automatically when something is merged into the trunk (it should not be possible to push into the trunk directly) and there is no tag.
      # - name: Integration Tests - ng11, Ivy off
      #   run: yarn integration:ng11:ivy:off

      ## All steps marked with this comment don't seem to be needed for tagged builds (aka releases), because each tagged build will happen only after a respective dev build,
      ## if releases are built off the trunk after dev builds.
      ## Dev builds happen automatically when something is merged into the trunk (it should not be possible to push into the trunk directly) and there is no tag.
      # - name: Integration Tests - ng11, Ivy
      #   run: yarn integration:ng11:ivy

      ## All steps marked with this comment don't seem to be needed for tagged builds (aka releases), because each tagged build will happen only after a respective dev build,
      ## if releases are built off the trunk after dev builds.
      ## Dev builds happen automatically when something is merged into the trunk (it should not be possible to push into the trunk directly) and there is no tag.
      # - name: Integration Tests - ng12, Ivy
      #   run: yarn integration:ng12:ivy

      ## All steps marked with this comment don't seem to be needed for tagged builds (aka releases), because each tagged build will happen only after a respective dev build,
      ## if releases are built off the trunk after dev builds.
      ## Dev builds happen automatically when something is merged into the trunk (it should not be possible to push into the trunk directly) and there is no tag.
      # - name: Integration Tests - ng13, Ivy
      #   run: yarn integration:ng13:ivy

      ## All steps marked with this comment don't seem to be needed for tagged builds (aka releases), because each tagged build will happen only after a respective dev build,
      ## if releases are built off the trunk after dev builds.
      ## Dev builds happen automatically when something is merged into the trunk (it should not be possible to push into the trunk directly) and there is no tag.
      # - name: Integration Tests - types
      #   run: yarn test:types

      ## All steps marked with this comment don't seem to be needed for tagged builds (aka releases), because each tagged build will happen only after a respective dev build,
      ## if releases are built off the trunk after dev builds.
      ## Dev builds happen automatically when something is merged into the trunk (it should not be possible to push into the trunk directly) and there is no tag.
      # - name: Check the size of NGXS bundle
      #   run: yarn bundlesize

      ## All steps marked with this comment don't seem to be needed for tagged builds (aka releases), because each tagged build will happen only after a respective dev build,
      ## if releases are built off the trunk after dev builds.
      ## Dev builds happen automatically when something is merged into the trunk (it should not be possible to push into the trunk directly) and there is no tag.
      # - name: Upload coverage results to Code Climate
      #   run: |
      #     curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > /tmp/cc-test-reporter
      #     chmod +x /tmp/cc-test-reporter
      #     /tmp/cc-test-reporter after-build --coverage-input-type lcov --exit-code 0
      #   env:
      #     CC_TEST_REPORTER_ID: 3f4c9a9d57ded045e0f9ab5d23e5bbcbf709bb85637bea555f1233e72134b818 # TODO: better store it in the repository secrets. Name the variable: CC_TEST_REPORTER_ID. Then delete this line and uncomment the next one
      #     # CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

      # TODO: uncommen after several test runs of the workflow
      # - name: Production release - publish tagged builds to all @ngxs packages
      #   run: |
      #     echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      #     yarn publish:tagged
      #     find ~/.npmrc -exec shred -fuz {} +
